spring:
  web:
    resources:
      add-mappings: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: mingke48@gmail.com
    password: ucukmkncensosgqq
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jwt:
    secret: ${JWT_SECRETKEY}

  security:
    user:
      name: yoursecurityName
      password: yoursecurityPassword

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hanyang?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 5242880 # 단일 요청 5MB

  profiles:
    active: dev

  cloud:
    aws:
      credentials:
        accessKey: ${AWS_S3_ACCESS_KEY}
        secretKey: ${AWS_S3_SECRET_ACCESS_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}
      cloudfront:
        url: ${CLOUDFRONT_URL}
      region:
        static: ap-northeast-2
      stack:
        auto: false

# 파일 저장 경로 추가
app:
  storage:
    path: ${STORAGE_PATH:/default/storage/files}
