spring:
#  web:
#    resources:
#      add-mappings: false

  jwt:
    secret: secretkey!jwt@43783732y874r4rutd44343

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hanyang?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create  # create는 매번 테이블 삭제 후 생성이므로 주의
    show-sql: true
    defer-datasource-initialization: true
