# application.yml (공통 설정)
spring:
  web:
    resources:
      add-mappings: false
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 5242880 # 단일 요청 5MB 5242880

# 파일 저장 경로 추가
app:
  storage:
    path: ${STORAGE_PATH:/default/storage/files} #임시
